// Animation names
#define ROCKETLAUNCHER_ANIM_CENTERED 0
#define ROCKETLAUNCHER_ANIM_FIRE 1
#define ROCKETLAUNCHER_ANIM_WAIT1 2
#define ROCKETLAUNCHER_ANIM_WAIT2 3
#define ROCKETLAUNCHER_ANIM_ACTIVATE 4
#define ROCKETLAUNCHER_ANIM_DEACTIVATE 5

// Color names

// Patch names

// Names of collision boxes
#define ROCKETLAUNCHER_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define ROCKETLAUNCHER_ATTACHMENT_BODY 0
#define ROCKETLAUNCHER_ATTACHMENT_MAGAZINE 1
#define ROCKETLAUNCHER_ATTACHMENT_ROTATINGPART 2
#define ROCKETLAUNCHER_ATTACHMENT_HAND 3

// Sound names
