// Animation names
#define SCORPNOGUN_ANIM_DEATH 0
#define SCORPNOGUN_ANIM_SCORPSOLDIER_FIRE 1
#define SCORPNOGUN_ANIM_SCORPSOLDIER_MELEE 2
#define SCORPNOGUN_ANIM_SCORPSOLDIER_IDLE 3
#define SCORPNOGUN_ANIM_SCORPSOLDIER_WOUND 4
#define SCORPNOGUN_ANIM_RUN 5
#define SCORPNOGUN_ANIM_SIGHT 6
#define SCORPNOGUN_ANIM_WALK 7

// Color names

// Patch names

// Names of collision boxes
#define SCORPNOGUN_COLLISION_BOX_PART_NAME 0
#define SCORPNOGUN_COLLISION_BOX_DEATH 1

// Attaching position names
#define SCORPNOGUN_ATTACHMENT_SCORPNOGUN 0

// Sound names
