// Animation names
#define TANKBOD_ANIM_TANK_FIRE 0
#define TANKBOD_ANIM_TANK_IDLEFIGHT 1
#define TANKBOD_ANIM_TANK_IDLELOW 2
#define TANKBOD_ANIM_TANK_MELEE 3
#define TANKBOD_ANIM_WALK 4
#define TANKBOD_ANIM_WOUND 5

// Color names

// Patch names

// Names of collision boxes
#define TANKBOD_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define TANKBOD_ATTACHMENT_TANKENGINE 0
#define TANKBOD_ATTACHMENT_TANKTHREADS 1
#define TANKBOD_ATTACHMENT_TANKTEETH 2
#define TANKBOD_ATTACHMENT_TANKCANNON 3
#define TANKBOD_ATTACHMENT_TANKCANNON2 4
#define TANKBOD_ATTACHMENT_TANKBARREL 5

// Sound names
