// Animation names
#define PRIMITIVE_ANIM_DEATH_BACK 0
#define PRIMITIVE_ANIM_DEATH_FRONT 1
#define PRIMITIVE_ANIM_DEATH_GIANT 2
#define PRIMITIVE_ANIM_IDLE_NOSHIELD 3
#define PRIMITIVE_ANIM_IDLE_SHIELD 4
#define PRIMITIVE_ANIM_MELEE_GIANT 5
#define PRIMITIVE_ANIM_MELEE_NOSHIELD 6
#define PRIMITIVE_ANIM_MELEE_SHIELD 7
#define PRIMITIVE_ANIM_RUN_NOSHIELD2 8
#define PRIMITIVE_ANIM_RUNATTACK_NOSHIELD2 9
#define PRIMITIVE_ANIM_THROWSHIELD 10
#define PRIMITIVE_ANIM_WALK_GIANT2 11
#define PRIMITIVE_ANIM_WALK_NOSHIELD2 12
#define PRIMITIVE_ANIM_WALK_SHIELD2 13
#define PRIMITIVE_ANIM_WOUND 14

// Color names

// Patch names

// Names of collision boxes
#define PRIMITIVE_COLLISION_BOX_PART_NAME 0
#define PRIMITIVE_COLLISION_BOX_DEATH 1

// Attaching position names
#define PRIMITIVE_ATTACHMENT_TEETH 0
#define PRIMITIVE_ATTACHMENT_BAT 1
#define PRIMITIVE_ATTACHMENT_SHIELD 2

// Sound names
