// Animation names
#define BUFFGNAAR_ANIM_DEFAULT_ANIMATION 0
#define BUFFGNAAR_ANIM_MORPHUP 1
#define BUFFGNAAR_ANIM_MORPHDOWN 2
#define BUFFGNAAR_ANIM_ATTACK02 3
#define BUFFGNAAR_ANIM_MORPHATTACKFLY 4
#define BUFFGNAAR_ANIM_MORPHATTACK 5
#define BUFFGNAAR_ANIM_DEATH01 6
#define BUFFGNAAR_ANIM_DEATH02 7
#define BUFFGNAAR_ANIM_MORPHDEATH 8
#define BUFFGNAAR_ANIM_FALL01 9
#define BUFFGNAAR_ANIM_FALL02 10
#define BUFFGNAAR_ANIM_STAND 11
#define BUFFGNAAR_ANIM_WOUND03 12
#define BUFFGNAAR_ANIM_WOUND06 13
#define BUFFGNAAR_ANIM_WOUND07 14
#define BUFFGNAAR_ANIM_MORPHWOUND01 15
#define BUFFGNAAR_ANIM_MORPHWOUND02 16
#define BUFFGNAAR_ANIM_WALK 17
#define BUFFGNAAR_ANIM_RUN 18
#define BUFFGNAAR_ANIM_ATTACK03 19

// Color names

// Patch names

// Names of collision boxes
#define BUFFGNAAR_COLLISION_BOX_GROUND 0
#define BUFFGNAAR_COLLISION_BOX_AIR 1
#define BUFFGNAAR_COLLISION_BOX_DEATH 2

// Attaching position names

// Sound names
