// Animation names
#define DEVILSTALLION_ANIM_FLYIDLE 0
#define DEVILSTALLION_ANIM_FLYATTACK 1
#define DEVILSTALLION_ANIM_FLYBREATH 2
#define DEVILSTALLION_ANIM_FLYWOUNDBACKWARD 3
#define DEVILSTALLION_ANIM_FLYWOUNDFORWARD 4
#define DEVILSTALLION_ANIM_FLYDEATH1 5
#define DEVILSTALLION_ANIM_FLYDEATH2 6
#define DEVILSTALLION_ANIM_LAND 7
#define DEVILSTALLION_ANIM_GROUNDIDLE 8
#define DEVILSTALLION_ANIM_GROUNDRUN 9
#define DEVILSTALLION_ANIM_GROUNDWALK 10
#define DEVILSTALLION_ANIM_GROUNDATTACK 11
#define DEVILSTALLION_ANIM_GROUNDBREATH 12
#define DEVILSTALLION_ANIM_GROUNDWOUNDBACKWARD 13
#define DEVILSTALLION_ANIM_GROUNDWOUNDFORWARD 14
#define DEVILSTALLION_ANIM_GROUNDDEATH 15
#define DEVILSTALLION_ANIM_LAUNCH 16

// Color names

// Patch names

// Names of collision boxes
#define DEVILSTALLION_COLLISION_BOX_INAIR 0
#define DEVILSTALLION_COLLISION_BOX_DEATH 1
#define DEVILSTALLION_COLLISION_BOX_ONGROUND 2

// Attaching position names

// Sound names
