// Animation names
#define WALKERMINIGUN_ANIM_DEFAULT_ANIMATION 0
#define WALKERMINIGUN_ANIM_STAND01 1
#define WALKERMINIGUN_ANIM_IDLEFIGHT 2
#define WALKERMINIGUN_ANIM_TOFIRE 3
#define WALKERMINIGUN_ANIM_FROMFIRE 4
#define WALKERMINIGUN_ANIM_FIRELEFT 5
#define WALKERMINIGUN_ANIM_FIRERIGHT 6
#define WALKERMINIGUN_ANIM_WALKBIG 7
#define WALKERMINIGUN_ANIM_WALK 8
#define WALKERMINIGUN_ANIM_DEATH 9

// Color names

// Patch names

// Names of collision boxes
#define WALKERMINIGUN_COLLISION_BOX_DEFAULT 0
#define WALKERMINIGUN_COLLISION_BOX_DEATH 1

// Attaching position names
#define WALKERMINIGUN_ATTACHMENT_MGA 0
#define WALKERMINIGUN_ATTACHMENT_MGB 1
#define WALKERMINIGUN_ATTACHMENT_MGC 2
#define WALKERMINIGUN_ATTACHMENT_MGD 3

// Sound names
