// Animation names
#define WALKERCANNON_ANIM_DEFAULT_ANIMATION 0
#define WALKERCANNON_ANIM_STAND01 1
#define WALKERCANNON_ANIM_IDLEFIGHT 2
#define WALKERCANNON_ANIM_TOFIRE 3
#define WALKERCANNON_ANIM_FROMFIRE 4
#define WALKERCANNON_ANIM_FIRELEFT 5
#define WALKERCANNON_ANIM_FIRERIGHT 6
#define WALKERCANNON_ANIM_WALKBIG 7
#define WALKERCANNON_ANIM_WALK 8
#define WALKERCANNON_ANIM_DEATH 9

// Color names

// Patch names

// Names of collision boxes
#define WALKERCANNON_COLLISION_BOX_DEFAULT 0
#define WALKERCANNON_COLLISION_BOX_DEATH 1

// Attaching position names
#define WALKERCANNON_ATTACHMENT_CANNON_LT 0
#define WALKERCANNON_ATTACHMENT_CANNON_RT 1

// Sound names
