// Animation names
#define SPIDERSMALL_ANIM_CLIMBDOWNSTRING 0
#define SPIDERSMALL_ANIM_DEATH 1
#define SPIDERSMALL_ANIM_DIGOUT 2
#define SPIDERSMALL_ANIM_FIRE_MOUTH 3
#define SPIDERSMALL_ANIM_HANGING 4
#define SPIDERSMALL_ANIM_HATCH_02 5
#define SPIDERSMALL_ANIM_HATCH_02_POSE 6
#define SPIDERSMALL_ANIM_IDLE 7
#define SPIDERSMALL_ANIM_MELEE 8
#define SPIDERSMALL_ANIM_UNDERGROUND 9
#define SPIDERSMALL_ANIM_WALK_DISCONTINIOUS 10
#define SPIDERSMALL_ANIM_WOUND 11

// Color names

// Patch names

// Names of collision boxes
#define SPIDERSMALL_COLLISION_BOX_PART_NAME 0
#define SPIDERSMALL_COLLISION_BOX_DEATH 1

// Attaching position names
#define SPIDERSMALL_ATTACHMENT_ELECTRICITY 0

// Sound names
